version: "1"
templates:
  - name: go
    source: git.target.com/vela/atlas/deploy/tap/go/template.yml
    type: github

steps:
  - name: go
    template:
      name: go
      vars:
        docker_path: app/skelly
        go_module: git.target.com/davidvader/skelly/cmd/skelly
        binary_output: release/skelly

  - name: dev_publish
    image: docker.target.com/vela-plugins/docker:v0.5.0-1
    pull: true
    parameters:
      cache: true 
      registry: docker.target.com
      repo: docker.target.com/app/skelly
      dockerfile: Dockerfile
      username: svcpejkn001
      tags:
        - latest
        - "b${BUILD_NUMBER}-${BUILD_COMMIT:0:8}"
        - "${BUILD_COMMIT:0:8}"
    ruleset:
      event: pull_request
    secrets: [ docker_password ]

secrets:
  - name: docker_password
    key: tap/vela-secrets/ARTIFACTORY_SVCPEJKN001_BINREPO
    engine: native
    type: shared